apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - name: demo-appcontainer
          image: docker.io/ritesh1372/demo_app:v1.0.0
          env:
            - name: RAILS_ENV
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: RAILS_ENV
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: POSTGRES_PASSWORD
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-sec 
                  key: RAILS_MASTER_KEY
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-storage
              mountPath: /rails/storage
      volumes:
        - name: app-storage
          emptyDir: {}
