name: Lint testing

on: workflow_dispatch


jobs:
  build:
    name: Rubocop Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      run: |
        ls 
        mv config/database.yml config/database.asc
        ls config/
