# Worflow example
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install gem 
      uses: luizfonseca/github-actions-rubocop@1.5.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
