name: RuboCop

on: workflow_dispatch

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Bundle Install
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop -P
