name: RuboCop

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop checks
      uses: prozsolt/rubocop-github-action@master
            
